# Generated by Django 3.0.7 on 2020-06-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametriGraficof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kol_vo_tovara', models.IntegerField(verbose_name='q ˗ количество товара')),
                ('price', models.FloatField(verbose_name='p ˗ цена')),
                ('udelnaia_stoimost_dotavki', models.FloatField(verbose_name='c ˗ удельная стоимость производства')),
                ('koefizent_discontirovania', models.FloatField(verbose_name='a(n,r) ˗ коэффициент дисконтирования')),
                ('negativ_vozdeistvia_na_obshestvo', models.FloatField(verbose_name='d ˗ негативное воздействие на качество жизни общества (социальный ущерб) в каждый период времени пропорционально объёму находящихся в окружающей среде загрязнений;')),
                ('obiem_zagriaz_veshestv', models.FloatField(verbose_name='e ˗ объем загрязняющего вещества на единицу товара')),
                ('dolia_nackoplenia_zagr_vechesatv', models.FloatField(verbose_name='δ ˗ доля накопленного загрязняющего вещества')),
                ('stavka_diskontirovania', models.FloatField(verbose_name='r ˗ ставка дисконтирования')),
                ('nachalnii_moment_vremeni', models.FloatField(verbose_name='t ˗ начальный момент времени')),
                ('investizii_v_rashirenie_proizvodstva', models.FloatField(verbose_name='f ˗ инвестиции в расширение производства')),
            ],
            options={
                'verbose_name': 'Параметры графиков',
                'verbose_name_plural': 'Параметры графиков',
            },
        ),
    ]
