# Generated by Django 3.0.7 on 2020-06-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametrigraficof',
            old_name='udelnaia_stoimost_dotavki',
            new_name='udelnaia_stoimost_proizvodstva',
        ),
        migrations.AddField(
            model_name='parametrigraficof',
            name='period',
            field=models.IntegerField(default=1, verbose_name='n ˗ период'),
            preserve_default=False,
        ),
    ]
