# Generated by Django 3.0.7 on 2020-06-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200606_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrigraficof',
            name='koefizent_discontirovania',
            field=models.FloatField(editable=False, verbose_name='a(n,r) ˗ коэффициент дисконтирования'),
        ),
    ]
