# Generated by Django 3.0.7 on 2020-06-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200606_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrigraficof',
            name='koefizent_discontirovania',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='a(n,r) ˗ коэффициент дисконтирования'),
        ),
    ]
