# Generated by Django 3.0.7 on 2020-06-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200606_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrigraficof',
            name='graniza_privlekatelnosti',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='beta - граница привлекательности инвестиций'),
        ),
        migrations.AddField(
            model_name='parametrigraficof',
            name='velichina_vigod',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='b3 ˗ величина выгод'),
        ),
    ]
