# Generated by Django 3.0.7 on 2020-06-06 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200606_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaborGraficov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('tip', models.CharField(choices=[('B3 и Beta', 'B3 и Beta'), ('B4 и Alpha', 'B4 и Alpha')], max_length=255, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Набор графиков',
                'verbose_name_plural': 'Набор графиков',
            },
        ),
        migrations.AddField(
            model_name='parametrigraficof',
            name='nabor_graficov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.NaborGraficov', verbose_name='Набор графиков'),
        ),
    ]
