# Generated by Django 3.0.7 on 2020-06-06 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200606_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrigraficof',
            name='nabor_graficov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parametri', to='core.NaborGraficov', verbose_name='Набор графиков'),
        ),
    ]
