# Generated by Django 3.0.7 on 2020-06-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200606_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='naborgraficov',
            name='skrit',
            field=models.BooleanField(default=False, verbose_name='Скрыть'),
        ),
    ]
