# Generated by Django 3.0.7 on 2020-06-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_naborgraficov_skrit'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrigraficof',
            name='b4',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='b4 ˗ величина выгод'),
        ),
    ]
