# Generated by Django 3.0.7 on 2020-06-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_parametrigraficof_b4'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrigraficof',
            name='alpha',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='alpha - граница привлекательности инвестиций'),
        ),
    ]
