# Generated by Django 3.0.7 on 2020-06-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_parametrigraficof_alpha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametrigraficof',
            options={'ordering': ['period'], 'verbose_name': 'Параметры графиков', 'verbose_name_plural': 'Параметры графиков'},
        ),
        migrations.AddField(
            model_name='naborgraficov',
            name='stroit_po',
            field=models.CharField(choices=[('kol_vo_tovara', 'q ˗ количество товара'), ('price', 'p ˗ цена'), ('udelnaia_stoimost_proizvodstva', 'c ˗ удельная стоимость производства'), ('koefizent_discontirovania', 'a(n,r) ˗ коэффициент дисконтирования'), ('negativ_vozdeistvia_na_obshestvo', 'd ˗ негативное воздействие'), ('obiem_zagriaz_veshestv', 'e ˗ объем загрязняющего вещества на единицу товара'), ('dolia_nackoplenia_zagr_vechesatv', 'δ ˗ доля накопленного загрязняющего вещества'), ('stavka_diskontirovania', 'r ˗ ставка дисконтирования'), ('nachalnii_moment_vremeni', 't ˗ начальный момент времени'), ('investizii_v_rashirenie_proizvodstva', 'f ˗ инвестиции в расширение производства')], default='price', max_length=255, verbose_name='Строить по'),
        ),
    ]
