# Generated by Django 3.0.7 on 2020-06-16 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200616_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='naborgraficov',
            name='dolia_nackoplenia_zagr_vechesatv',
            field=models.FloatField(default=1, verbose_name='δ ˗ доля накопленного загрязняющего вещества'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naborgraficov',
            name='investizii_v_rashirenie_proizvodstva',
            field=models.FloatField(default=1, verbose_name='f ˗ инвестиции в расширение производства'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naborgraficov',
            name='koefizent_discontirovania',
            field=models.FloatField(blank=True, null=True, verbose_name='a(n,r) ˗ коэффициент дисконтирования'),
        ),
        migrations.AddField(
            model_name='naborgraficov',
            name='kol_vo_tovara',
            field=models.IntegerField(default=1, verbose_name='q ˗ количество товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naborgraficov',
            name='nachalnii_moment_vremeni',
            field=models.FloatField(default=1, verbose_name='t ˗ начальный момент времени'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naborgraficov',
            name='negativ_vozdeistvia_na_obshestvo',
            field=models.FloatField(default=1, verbose_name='d ˗ негативное воздействие на качество жизни общества (социальный ущерб) в каждый период времени пропорционально объёму находящихся в окружающей среде загрязнений;'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naborgraficov',
            name='obiem_zagriaz_veshestv',
            field=models.FloatField(default=1, verbose_name='e ˗ объем загрязняющего вещества на единицу товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naborgraficov',
            name='periodov',
            field=models.IntegerField(default=10, verbose_name='Периодов'),
        ),
        migrations.AddField(
            model_name='naborgraficov',
            name='price',
            field=models.FloatField(default=1, verbose_name='p ˗ цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naborgraficov',
            name='sag',
            field=models.FloatField(default=0.1, verbose_name='Шаг'),
        ),
        migrations.AddField(
            model_name='naborgraficov',
            name='stavka_diskontirovania',
            field=models.FloatField(default=1, verbose_name='r ˗ ставка дисконтирования'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naborgraficov',
            name='udelnaia_stoimost_proizvodstva',
            field=models.FloatField(default=1, verbose_name='c ˗ удельная стоимость производства'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='naborgraficov',
            name='stroit_po',
            field=models.CharField(choices=[('kol_vo_tovara', 'q'), ('price', 'p'), ('udelnaia_stoimost_proizvodstva', 'c'), ('koefizent_discontirovania', 'a(n,r)'), ('negativ_vozdeistvia_na_obshestvo', 'd'), ('obiem_zagriaz_veshestv', 'e'), ('dolia_nackoplenia_zagr_vechesatv', 'δ'), ('stavka_diskontirovania', 'r'), ('nachalnii_moment_vremeni', 't'), ('investizii_v_rashirenie_proizvodstva', 'f')], default='price', max_length=255, verbose_name='Строить по'),
        ),
        migrations.AlterField(
            model_name='parametrigraficof',
            name='dolia_nackoplenia_zagr_vechesatv',
            field=models.FloatField(editable=False, verbose_name='δ ˗ доля накопленного загрязняющего вещества'),
        ),
        migrations.AlterField(
            model_name='parametrigraficof',
            name='investizii_v_rashirenie_proizvodstva',
            field=models.FloatField(editable=False, verbose_name='f ˗ инвестиции в расширение производства'),
        ),
        migrations.AlterField(
            model_name='parametrigraficof',
            name='kol_vo_tovara',
            field=models.IntegerField(editable=False, verbose_name='q ˗ количество товара'),
        ),
        migrations.AlterField(
            model_name='parametrigraficof',
            name='nabor_graficov',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parametri', to='core.NaborGraficov', verbose_name='Набор графиков'),
        ),
        migrations.AlterField(
            model_name='parametrigraficof',
            name='nachalnii_moment_vremeni',
            field=models.FloatField(editable=False, verbose_name='t ˗ начальный момент времени'),
        ),
        migrations.AlterField(
            model_name='parametrigraficof',
            name='negativ_vozdeistvia_na_obshestvo',
            field=models.FloatField(editable=False, verbose_name='d ˗ негативное воздействие на качество жизни общества (социальный ущерб) в каждый период времени пропорционально объёму находящихся в окружающей среде загрязнений;'),
        ),
        migrations.AlterField(
            model_name='parametrigraficof',
            name='obiem_zagriaz_veshestv',
            field=models.FloatField(editable=False, verbose_name='e ˗ объем загрязняющего вещества на единицу товара'),
        ),
        migrations.AlterField(
            model_name='parametrigraficof',
            name='period',
            field=models.IntegerField(editable=False, verbose_name='n ˗ период'),
        ),
        migrations.AlterField(
            model_name='parametrigraficof',
            name='price',
            field=models.FloatField(editable=False, verbose_name='p ˗ цена'),
        ),
        migrations.AlterField(
            model_name='parametrigraficof',
            name='stavka_diskontirovania',
            field=models.FloatField(editable=False, verbose_name='r ˗ ставка дисконтирования'),
        ),
        migrations.AlterField(
            model_name='parametrigraficof',
            name='udelnaia_stoimost_proizvodstva',
            field=models.FloatField(editable=False, verbose_name='c ˗ удельная стоимость производства'),
        ),
    ]
