# Generated by Django 3.0.7 on 2020-06-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200616_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naborgraficov',
            name='koefizent_discontirovania',
        ),
    ]
