# Generated by Django 3.0.7 on 2020-06-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_naborgraficov_koefizent_discontirovania'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naborgraficov',
            options={'ordering': ['id'], 'verbose_name': 'Набор графиков', 'verbose_name_plural': 'Набор графиков'},
        ),
        migrations.AlterField(
            model_name='naborgraficov',
            name='kol_vo_tovara',
            field=models.FloatField(verbose_name='q ˗ количество товара'),
        ),
        migrations.AlterField(
            model_name='naborgraficov',
            name='stroit_po',
            field=models.CharField(choices=[('kol_vo_tovara', 'q'), ('price', 'p'), ('udelnaia_stoimost_proizvodstva', 'c'), ('negativ_vozdeistvia_na_obshestvo', 'd'), ('obiem_zagriaz_veshestv', 'e'), ('investizii_v_rashirenie_proizvodstva', 'f')], default='price', max_length=255, verbose_name='Строить по'),
        ),
        migrations.AlterField(
            model_name='parametrigraficof',
            name='kol_vo_tovara',
            field=models.FloatField(editable=False, verbose_name='q ˗ количество товара'),
        ),
    ]
